# Basic
title: MelodyK's Den
subtitle: 心无旁骛，悠然自得
# welcome_message: <a href="http://yyksapple.com" target="_blank">Digital Age</a>
description: 一个喜欢敲敲打打的iOS Dev
creator: <a href="http://yyksapple.com">@onevcat</a>

url: "http://yyksapple.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: 我的项目, url: 'http://yyksapple.com'}
    - {title: 关于, description: 了解更多关于我, url: 'http://yyks999.github.io/welcome.html#/welcome'}
    - {title: 订阅, description: 邮件订阅本站, url: 'http://yyksapple.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: yyksapple
    github: yyks999
    twitter: Melody_Jiaozi
    gplus: 100061634606749947680
    mail: wyks999@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
